FROM renothing/php:5-fpm as builder
ARG TOKEN
RUN apk update && apk add git && \
    curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer 
RUN  composer global require "fxp/composer-asset-plugin:^1.3.1"
#    composer config -g github-oauth.github.com "${TOKEN}"
WORKDIR /var/www
# Expose volumes
#VOLUME ["/var/www"]
# Entry point
ENTRYPOINT ["/usr/bin/php"]
