FROM renothing/php:5-fpm as builder
ARG TOKEN
RUN apk update && apk add git && \
    curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer 
#    composer config -g github-oauth.github.com "${TOKEN}"
#start scripts
COPY run.dev.sh /opt/
WORKDIR /var/www
# Expose volumes
#VOLUME ["/var/www"]
# Entry point
ENTRYPOINT ["sh", "/opt/run.dev.sh"]
